### ISSUE TITLE
Bug - points de passage de la tempête

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#14]
Si l'on réinitialise les points de passage d'une tempête avant que celle-ci soit finie, on obtient divers bugs :
- La tempête s'immobilise au 5è point de passage et continue de tourner indéfiniment
- La tempête continue son chemin au-delà des points de passages initiaux puis s'arrête un peu plus tard
- La tempête "explose" et se disperse avant d'arriver au 5è point de passage initial
Il est également impossible de lancer une tempête après avoir réinitialisé les points de passages de la précédente car les nouveaux points de passages ne sont pas pris en compte.

----

Il faudrait dans un premier temps **empêcher l'utilisateur de réinitialiser les points de passages avec le bâton tempête (dans le cas où une tempête est déjà en cours exécution)**. S'il tente de cliquer avec le bâton pendant la tempête un message lui indiquerait " **Veuillez attendre la fin de la tempête**". Il peut néanmoins toujours utiliser le menu tempête pour arrêter celle-ci et une fois arrêtée il pourra replacer les points de passage.

**Comment by kilbith** [comment]
J'arrive pas à reproduire les 3 comportements étranges suscités quand la tempête arrive à terme. Il est fort possible que ça soit des glitchs causés par la latence réseau entre le serveur et le client.

La requête demandée pour la réinitialisation des points de passage : c'est fait.
