### ISSUE TITLE
Rayure verticale de non calcul des inondations dans le mapper

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#16]
Dans le cartographer, lorsque l'inondation est affichée, il apparaît des rayures verticales non calculées (ou non affichées) de l'inondation
Cela n'est pas spécifique à une carte (rencontré plusieurs fois)
Exemple sur Champigny sur Marne et les boucles de la Marne, emprise de 5km par 5km, montée des eaux de 6 m
A noter : lorsque l'eau redescend, le même phénomène se produit avec des rayures verticales de non calcul de la descente des eaux
![Rayure](https://user-images.githubusercontent.com/25570981/75678120-2d659e80-5c8d-11ea-89a1-97cb912558ff.jpg)

**Comment by pyrollo** [comment]
Testé : plus de bandes, même sur les grosses cartes.
