### ISSUE TITLE
Modification de l'infotexte "Héberger une partie"

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#18]
A la suite des changements apportés sur la façon pour les élèves de rejoindre un monde, il faudrait modifier l'infotexte (cf. pièce jointe) pour qu'il apparaisse comme suit : 

Cochez cette case pour que votre poste fasse office de serveur local. Indiquez
votre pseudonyme et laissez le port tel quel. Sélectionnez une carte et lancez le serveur. 
Vos élèves peuvent ensuite rejoindre votre monde depuis le menu "Rejoindre une partie".
Si votre serveur est en cours d'éxécution, il sera visible par tous les élèves. 
![Capture d’écran (445)](https://user-images.githubusercontent.com/25570981/75768376-847a7a80-5d44-11ea-8e26-53c1236a9d19.png)

**Comment by kilbith** [comment]
Fait.
