### ISSUE TITLE
Traduction dans le menu non effectuée

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#19]
Plusieurs mots ne sont pas traduits dans le menu principal. Il est important que les menus les plus utilisés soient tous traduits en français. 

1.  Lorsqu'on clique sur config. clavier dans le menu principal le mot "keybindings" apparaît. A la place il faut traduire par " Config. clavier ". 
2. Dans ce même menu, il faut traduire "toggle pitchmove" par "Déplacement via souris"

![Capture d’écran (446)](https://user-images.githubusercontent.com/25570981/75768745-3b76f600-5d45-11ea-9302-b405ca42c29e.png)

**Comment by kilbith** [comment]
Fait.
