### ISSUE TITLE
Renommer d'emblée la première carte importée

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#20]
Lorsqu'on n'a pas encore importé de carte dans le jeu, la première carte qu'on va importer sera automatiquement nommée minetest_alac. Ce n'est qu'à partir de la seconde carte que le jeu propose de choisir un titre pour celle-ci.

Il faudrait que le jeu offre la possibilité de donner un titre au monde systématiquement (donc dès la première map importée).

**Comment by pyrollo** [comment]
Fait, par contre on part avec un nom vide (et plus minetest_alac).
