### ISSUE TITLE
L'onglet Menu IGN n'apparaît pas dans le jeu

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#22]
![Capture d’écran (452)](https://user-images.githubusercontent.com/25570981/75865648-290fc180-5e04-11ea-97bb-7f0c267a207c.png)

**Comment by pyrollo** [comment]
Le mod "bucket" n'est plus dans le "minetest_game" mais xdecor en a besoin. C'est une mission pour @kilbith
