### ISSUE TITLE
Impossible de supprimer une carte

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#28]
Il est impossible de supprimer une carte dans le nouveau client, quand on clique sur le bouton rouge "Supprimer" pour confirmer, on est redirigé vers l'accueil du client mais la carte est toujours présente dans la liste.

**Comment by pyrollo** [comment]
Impossible à reproduire, ni sous Linux ni sous Windows, avec un client récent.

**Comment by forgecitizens** [comment]
Je n'ai plus eu ce problème depuis deux semaines je ferme donc.
