### ISSUE TITLE
Pouvoir importer une carte depuis une clé USB

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#31]
Il n'y a actuellement pas de possibilité de remonter à la racine (jusqu'au disque) pour aller chercher des cartes sur une clef USB.
Est-ce possible de mettre cela en place ?

**Comment by kilbith** [comment]
Est-ce toujours pertinent ?

**Comment by forgecitizens** [comment]
La demande reste ouverte si toutefois on pourra réaliser cela. Ce serait un plus pour le Ministère mais pas obligatoire
