### ISSUE TITLE
Interface d'accueil trop petite

### ISSUE THREAD

**Issue by ThomasLyy** [EvidenceBKidscode/kidscode#33]
Lorsque l'on lance Kidscode, le jeu est par défaut en petite fenêtre et l'interface est trop petite, le texte déborde des cases.

**Comment by forgecitizens** [comment]
@pyrollo On en a parlé hier, est-il possible de lancer le jeu par défaut en mode maximisé ? 
@ThomasLyy Pour info le moteur du jeu ne supporte pas le plein écran. Le mieux qu'on pourra faire c'est d'avoir une fenêtre maximisée.

**Comment by kilbith** [comment]
Je m'en occupe

**Comment by kilbith** [comment]
Fait.
