### ISSUE TITLE
Problème à l'import des cartes

### ISSUE THREAD

**Issue by ThomasLyy** [EvidenceBKidscode/kidscode#34]
Quand je souhaite importer une carte, rien n'apparaît dans l'arborescence, même en affichant "Tous les fichiers" et non pas juste "ZIP / RAR".

**Comment by forgecitizens** [comment]
Ca fonctionne sur mon client Thomas, as-tu la même version que le mien ? cf. le numéro de version en haut à gauche de ce screenshot 
![Capture d’écran (661)](https://user-images.githubusercontent.com/25570981/78347554-f4c52780-75a0-11ea-9e64-db77536b7ae0.png)

**Comment by ThomasLyy** [comment]
J'ai la version 5.2.0-45c8b0ccc-45c8b0ccc, mais j'ai résolu le soucis. Je crois que c'était parce que j'avais installé Kidscode sur mon HDD et qu'il pointait naturellement vers mon SSD, du coup probablement un conflit à ce niveau là ?

**Comment by kilbith** [comment]
Oui c'est normal. Le point d'entrée de l'arborescence ce sont les dossiers du système, pas les dossiers Kidscode.
