### ISSUE TITLE
"Entrée" pour importer une carte

### ISSUE THREAD

**Issue by ThomasLyy** [EvidenceBKidscode/kidscode#36]
Appuyer sur la touche "Entrée" pour valider le nom d'une carte importée ne fonctionne pas et fait revenir d'une étape en arrière (la sélection du fichier à importer).

**Comment by forgecitizens** [comment]
En effet mais je sais qu'il y a un problème pour utiliser certaines touches @pyrollo pourra confirmer. Actuellement la touche Entrée ne fait que lancer un monde sélectionné je ne sais pas dans quelle mesure c'est possible de lui attribuer une autre fonction.

**Comment by pyrollo** [comment]
@Kickback9000 la fonction dépend du formspec affiché.
La touche "Entrée" valide maintenant le nom de la carte.
À tester dans le prochain client.
