### ISSUE TITLE
Déclencher l'inondation d'une deuxième rivière totalement séparée de la première

### ISSUE THREAD

**Issue by LECORDIX** [EvidenceBKidscode/kidscode#37]
Si on a une carte avec 2 rivières indépendantes et qu'on veut faire monter l'eau sur l'une et l'autre rivière, il est impossible de sélectionner l'eau de la deuxième rivière après avoir sélectionné l'eau de la première rivière. On est bloqué sur l'eau de la première
Il faudrait un bouton pour repartir d'une autre source d'eau (pouvoir rouvrir le baton sélection d'eau)

**Comment by pyrollo** [comment]
Pour cela, il faut refaire un clic gauche avec le bâton d'eau sur l'autre surface d'eau. C'est elle qui va alors être contrôlée depuis le menu (et refaire un nouveau clic sur la première si l'on veut revenir dessus).
