### ISSUE TITLE
Message d'erreur après utilisation du bouton exit to menu

### ISSUE THREAD

**Issue by LECORDIX** [EvidenceBKidscode/kidscode#38]
Dans la version kidscode 5.2.0-45c8b0ccc-45c8b0cc (2020-04-05), lorsqu'on utilise le bouton exit to menu, lorsqu'on réouvre la carte le message" Irrlicht : Invalid size of image for OpenGL texture" apparaît

**Comment by kilbith** [comment]
Les messages d'erreur Irrlicht ne devraient plus apparaître dans le prochain client.
