### ISSUE TITLE
Non déclenchement de la montée des eaux sur une grande surface ?

### ISSUE THREAD

**Issue by LECORDIX** [EvidenceBKidscode/kidscode#39]
Sur la carte de 7km sur 7km de la Faute sur Mer, le déclenchement de la montée de l'eau sur mer ne donne rien : le calcul indique calcul terminé immédiatement sans rien faire .
Il y a-t-l un verrouillage si la surface est trop grande ? Il faudrait au minimum un message explicatif.
(PS  : la montée de l'eau se produit bien si on la déclenche sur un lac à coté)

**Comment by pyrollo** [comment]
Il y a deux problèmes possibles : 
- La position de départ choisie est en dehors de la zone de simulation (qui est petite pour cette carte, à priori +/- 500 autour du point 0, définie en fonction des données géographiques). Un message va être ajouté pour avertir quand cela se produit.
- Le remplissage rencontre des blocs vides qui n'ont pas encore d'existence sur la carte (le remplissage est bloqué par ces blocs). Une correction va être apportée.

**Comment by LECORDIX** [comment]
A priori, je dirais c'est l'option 1
Mais c'est dommage...
En fait j'ai centré la carte pour avoir toute l'emprise qui m'intéressait pour cartographier le phénomène concerné (et non centré sur l'endroit où je veux clqiuer)
Et ensuite je déclenche là où il y a la mer

**Comment by pyrollo** [comment]
La limite de la zone de simulation est donnée par le fichier geometry.dat. Elle correspond aux quatre coins donnés pour le calcul des coordonnées. Sur cette carte, ces coins sont en +-614, ce qui explique la surface réduite.
Par contre, sur de grandes cartes, comme celle-ci, les performances risquent d'être assez mauvaiseS.

**Comment by kilbith** [comment]
Les performances sont a priori très bonnes désormais y compris sur de larges surfaces.
