### ISSUE TITLE
Textes décalés et pas cadrés au lancement du jeu

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#40]
Le jeu se lance bien en mode fenêtre maximisée mais les textes sont décalés et trop gros.
Y'a-t-il une possibilité d'utiliser la résolution de l'écran actuellement active chez l'utilisateur et de calquer la résolution de kidscode dessus ? 
Sur le kidscode de base le jeu se calque bien sur ma résolution native sans que j'aie à modifier les paramètres. 

![Capture d’écran (669)](https://user-images.githubusercontent.com/25570981/78571782-e8ea9700-7826-11ea-8dce-a0da16917498.png)

**Comment by kilbith** [comment]
Corrigé avec a4d4494ea0550f6fd3750ddadf7482e34fa5277c
