### ISSUE TITLE
La carte Moutiers au Perche ne se télécharge pas + crash

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#42]
Je suis bloqué à l'écran de téléchargement depuis plus de dix minutes.
Quelqu'un peut essayer de la télécharger aussi et me dire si ça marche de votre côté ?
![Capture d’écran (678)](https://user-images.githubusercontent.com/25570981/78640450-0d3e8600-78b0-11ea-8ac5-18e2abfb0576.png)

**Comment by pyrollo** [comment]
Essayé avec un peu de retard, ça fonctionne bien chez moi.
Le lien direct pour cette carte afin de vérifier les pb de connexions : 
http://minecraftdl.ignfab.com/kidscode_alac-rcknW56it1fICOoi.zip

**Comment by forgecitizens** [comment]
Merci je regarde ;)

Le jeu. 9 avr. 2020 à 09:31, Pierre-Yves Rollo <notifications@github.com> a
écrit :

**Comment by forgecitizens** [comment]
J'ai pu l'importer sans problème et me connecter dessus mais j'ai eu un crash.
Pour info : j'ai fait un fresh install (supprimé tous les fichiers du jeu, les mondes, y compris les dossiers laissés sur le pc après désinstallation de l'ancien client). 

![Capture d’écran (718)](https://user-images.githubusercontent.com/25570981/78884717-b07fce80-7a5b-11ea-9836-69031ebd1559.png)

**Comment by forgecitizens** [comment]
Le message complet est ici : 
https://pastebin.com/mW0G9YLC

**Comment by kilbith** [comment]
Le std::bad_alloc me fait penser à un OOM de la machine Lua.

**Comment by kilbith** [comment]
@pyrollo Peut-être qu'on peut récupérer la librairie LuaJIT constuite avec un garbage collector en 64 bits dans le build officiel Windows de Minetest.

**Comment by kilbith** [comment]
https://github.com/EvidenceBKidscode/kidscode/issues/47 et https://github.com/EvidenceBKidscode/kidscode/issues/49 indiquent les mêmes erreurs dans les logs, c'est surement le même problème. Je ferme ces tickets pour éviter les doublons.

**Comment by pyrollo** [comment]
Pour mémoire, extrait du log:
```
2020-04-09 12:13:00: ERROR[Main]: ServerError: AsyncErr: Lua: finishGenRuntime error from mod 'respawn' in callback environment_OnGenerated(): std::bad_alloc
2020-04-09 12:13:00: ERROR[Main]: stack traceback:
2020-04-09 12:13:00: ERROR[Main]:   [C]: in function 'write_to_map'
2020-04-09 12:13:00: ERROR[Main]:   C:\Users\Andrei\AppData\Roaming\KidscodeIGN\worlds\Moutiers au Perche\worldmods\respawn\init.lua:20: in function <C:\Users\Andrei\AppData\Roaming\KidscodeIGN\worlds\Moutiers au Perche\worldmods\respawn\init.lua:16>
```

**Comment by forgecitizens** [comment]
Je ferme cela fonctionne avec le dernier client.
