### ISSUE TITLE
Page blanche au chargement de n'importe quel monde

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#43]
En chargeant n'importe quel monde installé une page blanche s'affiche par-dessus la fenêtre de jeu. Même une fois la carte chargée la page blanche reste affichée et je suis obligé d'appuyer sur le bouton Windows et de sélectionner à la souris la fenêtre du jeu. 

Cette fenêtre vide n'aparaissait pas dans les anciens clients.

![Capture d’écran (683)](https://user-images.githubusercontent.com/25570981/78640729-81792980-78b0-11ea-8996-39f8acdb8d73.png)

**Comment by pyrollo** [comment]
Corrigé dans le prochain client.
