### ISSUE TITLE
On ne peut plus casser des blocs en maintenant clic gauche enfoncé

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#44]
Il faut désormais cliquer une fois pour casser un bloc. Si on maintient le clic gauche enfoncé le bloc suivant ne se casse plus. 

Il faudrait remettre le paramètre qui existait avant par défaut sur les prochains clients.
![Capture d’écran (684)](https://user-images.githubusercontent.com/25570981/78643780-1847e500-78b5-11ea-91e8-e8f166636e21.png)

**Comment by LECORDIX** [comment]
La nouvelle version du 07/04/20 résout ce problème : en restant appuyer en clic gauche on casse plusieurs blocs

**Comment by forgecitizens** [comment]
Résolu chez moi aussi avec le dernier client.
