### ISSUE TITLE
L'interface n'as plus une taille unie sur tous les boutons et formspecs

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#45]
Il y a un gros décalage entre la taille de l'inventaire (qui ressemble plus à ce que l'on avait la semaine dernière) et la taille de la hotbar par exemple ou des boutons dans le menu échap. 
L'ensemble n'est plus aussi harmonieux qu'avant. 
![Capture d’écran (685)](https://user-images.githubusercontent.com/25570981/78644103-a328df80-78b5-11ea-8285-c1252ff73b4c.png)

**Comment by kilbith** [comment]
Je vais annuler les changements récents faits sur le DPI scaling

**Comment by kilbith** [comment]
Corrigé avec a4d4494ea0550f6fd3750ddadf7482e34fa5277c
