### ISSUE TITLE
Problème de lancement des cartes sur le cartographe

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#46]
Peu importe la carte sélectionnée, le cartographe n'en lance aucune et se ferme automatiquement.

**Comment by forgecitizens** [comment]
![Capture d’écran (688)](https://user-images.githubusercontent.com/25570981/78657491-23a50b80-78c9-11ea-9332-a49f5538a635.png)

**Comment by pyrollo** [comment]
Problème à résoudre avec le module UPNP qui se plante sur ton Windows (pas reproduit en virtualisé). Le module est désactivé en attendant.
