### ISSUE TITLE
Renommer l'éxécutable kidscode.exe en IGNkidscode.exe

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#48]
L'éxecutable est redevenu kidscode.exe ce qui crée des conflits lorsqu'on a deux installations de kidscode de base + kidscode IGN.

**Comment by pyrollo** [comment]
L'exécutable reste kidscode.exe mais le dossier d'installation, le dossier de données (là où il y a les cartes) ainsi que l'icone sur le bureau sont renommés en KidscodeIGN.
