### ISSUE TITLE
Utiliser la fonction "avancer plus vite" du bouton "E" (par défaut) dans les airs aussi

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#50]
Quand on est au sol et qu'on appuie sur "E" on avance beaucoup plus vite. Or, cette fonctionnalité très utile ne marche pas quand on est en train de voler. Est-il possible de la rendre active quand on vole aussi ? 

Edit : Je constate que la vitesse qu'on obtient au sol en appuyant sur "E" est identique à celle que l'on obtient automatiquement en volant si on active vitesse rapide avec la touche "J".

Ce qui serait intéressant, c'est qu'en appuyant sur "E" une fois dans les airs (et dès lors que la touche J a été enclenchée) on puisse avancer aussi vite que si on avait activé le bouton vitesse x2 du menu IGN. 

On pourrait ainsi se passer du bouton vitesse x2 du menu IGN et garder toutes les options de déplacement rapide, et très rapide sur le clavier (qu'on soit au sol ou dans les airs).

**Comment by kilbith** [comment]
Fait.
