### ISSUE TITLE
Problème d'affichage des points de passage de la tornade

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#52]
Les points de passage apparaissent désormais en noir peu importe où je les place.
![Capture d’écran (719)](https://user-images.githubusercontent.com/25570981/78894758-f5acfc00-7a6d-11ea-853c-9d925b7dbb9a.png)

**Comment by kilbith** [comment]
Corrigé.

@pyrollo Il faudrait faire un pull sur upstream comme 5.2 est enfin sorti.

**Comment by pyrollo** [comment]
C'est noté pour le pull.
