### ISSUE TITLE
Chute drastique des fps lors d'une tornade très grande

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#53]
La tornade petite et moyennent fonctionnent convenablement (entre 30 et 55 fps) mais lors d'une très grande tornade je tombe à 4 fps. 

![Capture d’écran (720)](https://user-images.githubusercontent.com/25570981/78894932-4290d280-7a6e-11ea-9bcf-d3cebe78134d.png)

**Comment by kilbith** [comment]
C'est normal, c'est lié à un grand nombre d'entités. On peut pas faire grand chose dessus.
