### ISSUE TITLE
Blocs noirs qui apparaissent dans la tornade

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#54]
Beaucoup de blocs noirs apparaissent dans les tornades. Comment puis-je savoir de quel bloc il s'agit en particulier ? 
![Capture d’écran (722)](https://user-images.githubusercontent.com/25570981/78906516-bd161e00-7a7f-11ea-88e3-99f6f298ad8d.png)

**Comment by kilbith** [comment]
C'est surement le même problème que ça : https://github.com/EvidenceBKidscode/kidscode/issues/52

Mais ça été corrigé.
