### ISSUE TITLE
Fenêtre qui porte à confusion lors d'une connexion à un serveur

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#55]
Quand on se connecte au serveur d'un prof, même si ce dernier n'aura pas défini de mot de passe pour le serveur, une fenêtre demande quand même d'entrer le mot de passe et de s'enregistrer. Celle-ci n'a pas lieu d'être sauf si l'enseignant a mis un mot de passe mais si ce n'est pas le cas elle ne devrait pas apparaître. 

Sur la fenêtre qui devrait apparaître il faudrait simplement demander à l'utilisateur d'entrer le mot de passe du serveur (si applicable).

![Capture d’écran (728)](https://user-images.githubusercontent.com/25570981/79310322-08a34e80-7efc-11ea-9cf8-354e0d98e1a1.png)

**Comment by kilbith** [comment]
Il n'y a pas de de mot de passe du serveur, un mot de passe c'est nécessairement personnel. En outre, dans tous les formulaires d'inscription existants sur le web, on demande **toujours** une confirmation du mot de passe, ce qui me parait logique.

**Comment by forgecitizens** [comment]
Ok mais ça ne fait pas de sens de demander un mot de passe à l'utilisateur à ce stade du jeu étant donné que dans l'onglet "Rejoindre un serveur" l'utilisateur a choisi de ne pas mettre de mot de passe.
C'est bien écrit " please retype your password " or c'est pas logique qu'on demande ça aux élèves à moins qu'ils aient choisi au préalable un mot de passe depuis le menu "rejoindre un serveur".

**Comment by kilbith** [comment]
Alors si l'utilisateur choisit de ne pas rentrer de mot de passe, cette fenêtre ne devrait pas s'afficher. Si il en a choisi un par contre, il est fortement recommandé de lui demander une confirmation pour éviter qu'il entre un mot de passe mal tapé (et donc non-mémorisable) lors de la première saisie.

**Comment by kilbith** [comment]
A tester : https://github.com/EvidenceBKidscode/kidscode/commit/b70187ff44cc0135fddb52440b9556a9d4e930e9

**Comment by forgecitizens** [comment]
Oui c'est exactement ça il ne faut juste pas qu'elle s'affiche quand on n'a pas choisi de mot de passe au préalable ;)

**Comment by kilbith** [comment]
Est-ce que mon commit a été testé ?

**Comment by forgecitizens** [comment]
@kilbith @pyrollo 
Testé avec le client de ce matin aussi. La création de serveur local fonctionne. Mais quand je veux connecter un deuxième user sans avoir attribué de mot de passe je bloque sur la fenêtre de chargement 
![Capture d’écran (812)](https://user-images.githubusercontent.com/25570981/80214459-27f85500-863b-11ea-8b84-d136c702d086.png)

**Comment by kilbith** [comment]
Alors j'ai testé exactement dans les mêmes conditions et je suis arrivé à me connecter sans qu'on me demande une confirmation de mot de passe.

**Comment by forgecitizens** [comment]
Je reste demain c'est tordu cette histoire

**Comment by kilbith** [comment]
Est-ce toujours d'actualité ?

**Comment by forgecitizens** [comment]
Non je ferme ;)
