### ISSUE TITLE
Bug dans la feature "area protect" - bouton Autoriser la construction

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#57]
Quand on veut modifier les autorisations au sein d'une zone protégée , en cliquant par exemple sur "Autoriser la destruction" on retourne automatiquement au menu précèdent. 

![Capture d’écran (734)](https://user-images.githubusercontent.com/25570981/79345757-ceed3a80-7f31-11ea-8dff-6fe8620b12ce.png)

**Comment by kilbith** [comment]
Tu veux dire que lorsque tu cliques sur ces entrées dans les listes déroulantes, tu reviens immédiatement au menu précédent ? Chez moi ça le fait pas en tout cas.

**Comment by forgecitizens** [comment]
Pardon ton message est passé à la trappe oui c'est ça je reviens en arrière dès que je clique sur une entrée. @pyrollo tu pourras tester de ton côté aussi s'il te plaît ? Merci

**Comment by pyrollo** [comment]
Pareil chez moi (mais sur d'autres formspec de worldedit, pas de pb).

**Comment by pyrollo** [comment]
Je suis en train de revoir la partie Area de Worldedit

**Comment by pyrollo** [comment]
C'est corrigé.
