### ISSUE TITLE
WorldEdit : Défilement étrange des pages de sélection de blocs

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#61]
Par exemple dans la feature "set nodes" du World Edit et dans toute autre feature affichant l'inventaire complet , quand on clique sur flèche gauche ou droite pour faire défiler les blocs ceux-ci défilent ligne après ligne. 
Il faudrait qu'ils défilent page par page par exemple ou alors une colonne à la fois. 
![Capture d’écran (745)](https://user-images.githubusercontent.com/25570981/79553780-51463d80-809d-11ea-99af-aa357cb623ef.png)

**Comment by kilbith** [comment]
Corrigé.
