### ISSUE TITLE
Bug avec le clic molette

### ISSUE THREAD

**Issue by ThomasLyy** [EvidenceBKidscode/kidscode#63]
##### Minetest version

```
5.2.0-ed1a736e9-ed1a736e9
```

##### OS / Hardware

Operating system: Windows 10
CPU: i7-4790K

##### Summary
Si l'on effectue un clic molette vers un bloc avec, en main, un bloc impossible à placer (style seau ou autre), le jeu crash avec l'erreur suivante :
AsyncErr: environment_Step: Runtime error from mod 'utils' in callback environment_Step(): "bucket:bucket_lava" is not a registered node!
stack traceback:
[C]: in function 'set_node'
[string "C:\Program Files\EvidenceB\Kidscode\bin...\ga..."]:154: in function <[string "C:\Program Files\EvidenceB\Kidscode\bin...\bu..."]:122>
[string "C:\Program Files\EvidenceB\Kidscode\bin...\ga..."]:429: in function <[string "C:\Program Files\EvidenceB\Kidscode\bin...\bu..."]:413>
stack traceback:

##### Steps to reproduce
Avoir en main un objet style seau ou morceau d'argile et effectuer un clic molette vers un autre bloc

**Comment by pyrollo** [comment]
Corrigé, le click de la molette de fait plus rien si l'on tient un objet non plaçable.
