### ISSUE TITLE
World Edit - Cacher complétement le bouton " Features avancées "

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#64]
Trop de fonctionnalités avancées du world edit donnent lieu à des comportements aléatoires. Par exemple " cancel action " n'annule quasiment jamais l'action précèdente mais modifie des blocs qu'on ne veut pas modifier. 
Vu qu'on ne peut pas supprimer ces fonctions avancées il faudrait :
1. Enlever le bouton "Avancé" du menu World Edit
2. Ajouter les features "set nodes" et "copy/move" dans le menu de base du world edit car ce sont des features pratiques pour les constructions de base et ne buguent pas. 

![Capture d’écran (751)](https://user-images.githubusercontent.com/25570981/79734486-12132900-82f7-11ea-93ce-4af0b786b6cb.png)

**Comment by forgecitizens** [comment]
![worldedit](https://user-images.githubusercontent.com/25570981/79734546-30792480-82f7-11ea-9d3d-670784912d96.png)

**Comment by kilbith** [comment]
Fait.
