### ISSUE TITLE
Mod xpanes - problème d'affichage des textures des nodes

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#65]
Les nodes du mod xpanes affichent un contour bleu. Certains blocs issus de ce mod comme les grilles de bambou, lorsqu'on les détruit, affichent un message d'erreur dans le jeu. 
![Capture d’écran (756)](https://user-images.githubusercontent.com/25570981/79743458-e6973b00-8304-11ea-8f50-7bf130fe9a51.png)

![Capture d’écran (754)](https://user-images.githubusercontent.com/25570981/79743472-eb5bef00-8304-11ea-87ea-1c89f8972969.png)

![Capture d’écran (755)](https://user-images.githubusercontent.com/25570981/79743479-eeef7600-8304-11ea-9844-a04f004a771c.png)

**Comment by pyrollo** [comment]
Corrigé
