### ISSUE TITLE
Fonction "rechercher" de l'inventaire ne prend pas en compte le français

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#67]
Beaucoup de blocs sont introuvables via la fonction "rechercher" de l'inventaire si on utilise le français.
Par exemple, si j'écris "bois" je n'obtiens qu'un seul bloc en bois comme résultat alors qu'avec "wood" je les retrouve tous. 
![Capture d’écran (792)](https://user-images.githubusercontent.com/25570981/79984115-ff405600-84a8-11ea-919b-e0b96862b97e.png)

![Capture d’écran (793)](https://user-images.githubusercontent.com/25570981/79984123-036c7380-84a9-11ea-9e7c-330c14029dd3.png)

**Comment by kilbith** [comment]
@pyrollo C'est à cause des traductions côté client. `def.description` reste malgré tout en anglais alors qu'avant avec `intllib` les traductions se faisaient au chargement du jeu.

**Comment by pyrollo** [comment]
Oui, j'essaye de voir s'il est possible de charger les traductions FR côté serveur même si c'est un peu tordu.

**Comment by pyrollo** [comment]
C'est corrigé, ça prend maintenant en compte le français, l'anglais et le nom technique de l'item.

**Comment by kilbith** [comment]
Mais du coup upstream doit avoir le même problème, il serait peut-être judicieux de backporter ces patchs pour revue.

**Comment by pyrollo** [comment]
C'est fait !

**Comment by forgecitizens** [comment]
C'est mieux que la dernière fois mais on voit encore une grande différence. Pas la peine de travailler plus que ça dessus pour le moment mais à garder de côté pour plus tard.

![Capture d’écran (806)](https://user-images.githubusercontent.com/25570981/80192160-10a77080-8617-11ea-9d55-3828143c758d.png)

![Capture d’écran (807)](https://user-images.githubusercontent.com/25570981/80192250-30d72f80-8617-11ea-9229-0f92b417074c.png)

**Comment by pyrollo** [comment]
Ok, en fait c'est dû au fait que les noms techniques des blocs comportent le mot "wood". Par exemple "barrière en chêne" se nomme "oak_wood_fence" (qui n'est jamais traduit). On n'a jamais le mot "bois". La seule solution serait de nommer les items "barrière en bois de chêne".
