### ISSUE TITLE
Mettre à jour le fichier des nodes à garder dans le jeu

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#68]
Avec la nouvelle version de Minetest il y a eu trop de blocs inutiles qui se sont ajoutés au jeu.
Utiliser la liste ci-jointe pour ne garder que ces nodes-là dans le jeu.
Je verrai avec le prochain client si tout a été bien supprimé. 
[kc_list.txt](https://github.com/EvidenceBKidscode/kidscode/files/4516870/kc_list.txt)

**Comment by kilbith** [comment]
La liste est incomplète, il manque des nodes importants car ils sont placés par la mapgen tels que :

```
default:silver_sand
default:cobble
```

**+** les fleurs, les papillons, les pousses d'arbres, les plants de coton et les barrières en bois. Et probablement d'autres nodes importants et très utilisés.

Merci de rectifier.

**Comment by forgecitizens** [comment]
@pyrollo  Tu pourras faire une liste à jour ? Si possible en utilisant celle que j'ai déjà mis à jour et ne rajouter que ce dont Jean Patrick a besoin. Merci

**Comment by pyrollo** [comment]
Il manquait les alias dans la liste d'origine.

Je t'ai fait quatre listes : alias d'un côté, nodes et items de l'autre, à garder et à supprimer.

[Alias à conserver.txt](https://github.com/EvidenceBKidscode/kidscode/files/4521899/Alias.a.conserver.txt)
[Alias à supprimer.txt](https://github.com/EvidenceBKidscode/kidscode/files/4521900/Alias.a.supprimer.txt)
[Node et items à conserver.txt](https://github.com/EvidenceBKidscode/kidscode/files/4521901/Node.et.items.a.conserver.txt)
[Node et items à supprimer.txt](https://github.com/EvidenceBKidscode/kidscode/files/4521902/Node.et.items.a.supprimer.txt)

**Comment by forgecitizens** [comment]
@kilbith  A partir de là de quoi as-tu besoin comme fichier exactement ? Est-ce que tu veux un fichier seul avec les alias et les nodes items à conserver ? Ou est-ce que tu veux à la fois les nodes/items/alias à conserver et les nodes/items/alias à supprimer dans un fichier différent ?

**Comment by kilbith** [comment]
C'est bon pour moi

**Comment by kilbith** [comment]
Franchement c'est n'importe quoi les fichiers des alias... Je ne sais pas à quoi correspond ces items qui sont listés un à un et vers quoi ils sont aliasés...

**Comment by kilbith** [comment]
Y'a pas non plus la nécessité de faire une liste des items à supprimer. Tout ce qui ne figure pas dans les items à conserver doit être éliminé.

**Comment by kilbith** [comment]
Bon j'ai poussé ça mais c'est encore incomplet, il manque des nodes essentiels utilisés par la mapgen : https://github.com/EvidenceBKidscode/ign/commit/89e56cebe2a3b32e2e28d6a5756d9e33c330c2a1

Je laisse la main à @pyrollo pour les questions de suppression d'items car les demandes ne sont pas carrées.

**Comment by pyrollo** [comment]
Ca a l'air d'être bon maintenant.

**Comment by kilbith** [comment]
`2020-04-29 04:31:09: ERROR[Server]: Item "kidsblocks_native:cobblestone" not defined at position (43,10,5)`
