### ISSUE TITLE
Impossible de casser des blocs 

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#69]
Sur le client du 24 Avril, je ne peux pas casser de blocs pourtant j'ai bien tous les privilèges requis.
Aussi, lorsque j'essaie de casser je vois sur le mouvement du bras que le bras est plus petit qu'avant. 
![Capture d’écran (804)](https://user-images.githubusercontent.com/25570981/80188922-28302a80-8612-11ea-8206-76b45324c1ae.png)

**Comment by pyrollo** [comment]
Corrigé.
