### ISSUE TITLE
Items rétractables - Item stairs:stair not defined

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#70]
Le mod fonctionne très bien avec les nodes compatibles workbench. Pour quelques blocs seulement il manque simplement le stairs:stair qui n'est pas défini. 

default:sandstone_normal_2 
default:stone_2
default:stone_andesite_smooth_2
default:stone_diorite_2
default:stone_diorite_smooth_2
default:stonebrick_2
default:stonebrick_cracked_2
hardenedclay:hardened_clay
hardenedclay:hardened_clay_black
hardenedclay:hardened_clay_blue
hardenedclay:hardened_clay_brown
hardenedclay:hardened_clay_cyan
hardenedclay:hardened_clay_gray
hardenedclay:hardened_clay_green
hardenedclay:hardened_clay_light_blue
hardenedclay:hardened_clay_light_gray
hardenedclay:hardened_clay_lime
hardenedclay:hardened_clay_magenta
hardenedclay:hardened_clay_orange
hardenedclay:hardened_clay_pink
hardenedclay:hardened_clay_purple
hardenedclay:hardened_clay_red
hardenedclay:hardened_clay_white
hardenedclay:hardened_clay_yellow

**Comment by kilbith** [comment]
Ça fait une 1h30 que je cherche, je trouve pas l'origine de ce problème :(

**Comment by kilbith** [comment]
Le problème vient de ça : https://github.com/EvidenceBKidscode/kidscode/issues/79#issuecomment-624078307

Il faut ajouter chaque node dans la whitelist.

**Comment by kilbith** [comment]
Problème réglé avec le passage à la blacklist (normalement).
