### ISSUE TITLE
Items rétractables - Les nodes issus de "kidsblocks_native" sont incompatibles

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#71]
Si tel est le cas, il faudrait alors les enlever de la liste des nodes rétractables et ne garder que le reste. 

![Capture d’écran (805)](https://user-images.githubusercontent.com/25570981/80191494-13559600-8616-11ea-809f-2853a0d2f307.png)

**Comment by kilbith** [comment]
Corrigé.

**Comment by forgecitizens** [comment]
J'ai encore le problème sur le client d'aujourd'hui 

![Capture d’écran (824)](https://user-images.githubusercontent.com/25570981/80580755-5e075180-8a0c-11ea-86e1-196cbdd88479.png)

**Comment by kilbith** [comment]
Erreur bête. Corrigé.
