### ISSUE TITLE
/map donne lieu à un crash + message d'erreur

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#72]
Message disponible ci-dessous
https://pastebin.com/SxUVL0nE

![Capture d’écran (809)](https://user-images.githubusercontent.com/25570981/80197931-a941ee80-861f-11ea-9331-3b51fa54a68c.png)

**Comment by pyrollo** [comment]
Corrigé, la command n'a plus lieu d'être, elle a été supprimée.
