### ISSUE TITLE
Créer une fenêtre d'accueil dès lors qu'on rejoint un monde 

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#73]
Cette fenêtre s'affiche dès lors que **l'on rejoint un monde pour la première fois**. 
Elle comporte plusieurs boutons cliquables qui renvoient vers une page associée.
L'utilisateur clique sur un choix et on lui présente des informations de base concernant ce qu'il souhaite faire. (cf. pdf en pièce jointe)
[Mockup_formspec_accueil_ingame.pdf](https://github.com/EvidenceBKidscode/kidscode/files/4546022/Mockup_formspec_accueil_ingame.pdf)

PS : le pdf est interactif

**Comment by kilbith** [comment]
Fait.
