### ISSUE TITLE
Mods inutiles à enlever définitivement du jeu

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#74]
Etant donné que les maps IGN n'utilisent pas les blocs de ces mods pour être correctement affichées et que nous n'avons pas du tout besoin de ces mods il faudrait à l'avenir les enlever définitivement de notre version de kidscode.

Merci de m'informer à l'avance si la suppression d'un mod dans la liste peut créer des conflits ou s'il est dépendant d'un mod important. 

Mods en question :
Binoculars
Boats
Bones
Bucket
Butterflies
Dye
Fireflies
Sethome
Vessels

**Comment by kilbith** [comment]
Fait.

**Comment by kilbith** [comment]
@pyrollo Apparemment le mod `map` dépend du mod `dye`...

**Comment by pyrollo** [comment]
Ok, je vais le virer aussi, il ne nous sert à rien map.

**Comment by pyrollo** [comment]
@kilbith j'ai eu aussi un pb avec xdecor dépendant de bucket. 
Pour résoudre en mode bourrin j'ai juste mis bucket en optionel.
Est-ce que tu peux regarder dans xdecor ce que ça risque de ne pas avoir ce mod ?
