### ISSUE TITLE
Afficher quelques informations pratiques ingame

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#75]
En suivant le .pdf ci-joint, afficher d'abord les commandes de base dans un rectangle gris à droite de l'écran en veillant bien à ce qu'elles apparaissent telles que présentées dans le .pdf 

Enfin, afficher les messages dans le chat dès lors que l'utilisateur active le vote vol ou le mode noclip.

"Mod vol activé. Touche Espace pour vous élever, Shift Gauche pour descendre, E pour accélerer. A combiner avec Z,S,Q,D"

"Mode fantôme activé. Pour passer à travers les murs et obstacles commencez par voler"

**Comment by forgecitizens** [comment]
[AidesContextuelles.pdf](https://github.com/EvidenceBKidscode/kidscode/files/4546242/AidesContextuelles.pdf)

**Comment by kilbith** [comment]
Fait.

**Comment by forgecitizens** [comment]
Très bien pour les commandes de base, seulement les messages quand on active le mode vol et noclip disparaissent très vite (en moins d'une seconde chez moi). Il faut augmenter la durée d'apparition de ces messages (5 secondes ce serait bien).

**Comment by kilbith** [comment]
J'y pensais hier soir avant de me coucher - c'est fait.

**Comment by forgecitizens** [comment]
Je rouvre ce ticket parce que dans le dernier client reçu l'affichage des infos disparaît à nouveau au bout d'une seconde.

**Comment by pyrollo** [comment]
C'est peut être parce que le dernier client était sur une branche non fusionnée (du coup les modifs récentes de JP n'y étaient pas).

**Comment by kilbith** [comment]
Quelle branche non-fusionnée ?

**Comment by pyrollo** [comment]
La branche sur laquelle je développais l'intégration du mapserver. Elle est fusionnée maintenant.

**Comment by forgecitizens** [comment]
Update : avec le client de ce matin je n'ai plus les informations relatives au mode vol activé et mode fantôme activé qui apparaissent. J'ai simplement les infos de base de Minetest :
"Mode vol activé"
"Noclip activé"

**Comment by pyrollo** [comment]
Bizarre, je viens de regarder, je les ai bien (sous windows).

Le numéro du client testé est : 6d35ce924

**Comment by forgecitizens** [comment]
Résolu
