### ISSUE TITLE
Superedit - enlever toutes les images contenues dans le mod 

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#76]
Dans le mod Superedit il y a beaucoup d'images que nous n'utilisons pas pour la version IGN. Il faudrait toutes les enlever dans les prochains packages sauf naturellement la texture de l'outil superedit et de l'infoblock. 
![Capture d’écran (829)](https://user-images.githubusercontent.com/25570981/80606294-6ecbbd80-8a34-11ea-8be5-3dce9c4bee1a.png)

**Comment by kilbith** [comment]
Fait.

@pyrollo J'ai créé une branche `ign` pour le mod `superedit`.
