### ISSUE TITLE
Déplacer le guide d'utilisation vers un nouvel onglet

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#77]
Pour rester cohérent avec ce qui est écrit dans la fenêtre d'accueil sur chaque monde, il faudrait créer un onglet "Aide" à droite de l'onglet IGN,  en utilisant la texture ci-jointe pour cet onglet. 

Il faudrait ensuite que le guide d'utilisation, actuellement situé dans le menu IGN, n'apparaisse plus que dans cet onglet "Aide". Cela nous laissera un espace supplémentaire de libre dans le menu IGN pour une prochaine fonctionnalité liée aux outils de géographie/carto/scénarios.

[help_icons.zip](https://github.com/EvidenceBKidscode/kidscode/files/4557610/help_icons.zip)

**Comment by kilbith** [comment]
Fait. Deux remarques cependant :

1. J'ai essayé la texture suggérée et elle ne rend pas bien du tout, du coup j'ai conservé l'actuelle :

![screenshot_20200430_171428](https://user-images.githubusercontent.com/7883281/80727733-5f1ca980-8b06-11ea-9f30-8648ecf3f546.png)

2. Il faut une texture en 64x64px pour l'onglet IGN.
