### ISSUE TITLE
Supprimer définitivement refi_texture pack

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#78]
Erreur de ma part, ce texture pack ne fait que ralentir la vitesse de chargement des mondes. Je l'ai supprimé chez moi et les mondes chargent trois fois plus vite donc à enelever définitivement.

PS : je n'ai pas eu de conflits ni de bugs après suppression de celui-ci mais à vérifier de votre côté aussi.

**Comment by kilbith** [comment]
Fait.
