### ISSUE TITLE
Ajouter ces nouveaux blocs dans l'inventaire

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#79]
Il faudrait créer dans le jeu les blocs inclus dans le dossier .zip et les ajouter à l'inventaire créatif avec leur textures respectives. On mettra certaines dans la boîte à outils IGN mais pas tout de suite. 

J'ai inclus la description en EN et en FR qui devra apparaître dans les infobulles. 

Les textures sont libres de droit et trouvées sur internet.
[new_materials.zip](https://github.com/EvidenceBKidscode/kidscode/files/4574015/new_materials.zip)

**Comment by kilbith** [comment]
https://github.com/EvidenceBKidscode/minetest_game/commit/f2c27455844414

@pyrollo pour une raison inconnue, les nodes ne sont pas ajoutés dans le jeu.
@Kickback9000  les textures pour `glass_brick` sont manquantes.

**Comment by forgecitizens** [comment]
[new_materials.zip](https://github.com/EvidenceBKidscode/kidscode/files/4579513/new_materials.zip)
@kilbith  au temps pour moi elle y est dans ce .zip

**Comment by pyrollo** [comment]
> @pyrollo pour une raison inconnue, les nodes ne sont pas ajoutés dans le jeu.

Ils manquent dans à la white list de ign_utils/mods_integration.lua

**Comment by kilbith** [comment]
Si on doit ajouter chaque node à chaque fois dans la whitelist, c'est super relou !

**Comment by kilbith** [comment]
Cette fois-ci les nodes sont ajoutés, par contre leurs variantes dans les items rétractables apparaissent comme inconnues. Il faut les rajouter dans la whitelist mais il y a en des centaines, ça prendrait énormément de temps, il faudrait plutôt avoir une blacklist plutôt qu'une whitelist qui est beaucoup trop fastidieuse à maintenir.

**Comment by forgecitizens** [comment]
Merci @kilbith donc si je comprends bien tu as besoin d'une blacklist qui comporte uniquement les nodes dont on ne veut pas afficher les items rétractables c'est ça ?

**Comment by kilbith** [comment]
Oui exact
