### ISSUE TITLE
Superposition des éléments sur la boussole

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#80]
Chez François, avec le client du Jeudi 31 Avril il a une superposition des éléments dans le menu avec la boussole. Je n'ai pas ce problème chez moi...
![Superposition](https://user-images.githubusercontent.com/25570981/80961708-ca6ac200-8e0b-11ea-94bb-776d66b0a23d.jpg)

**Comment by kilbith** [comment]
@pyrollo serait-ce lié à `z_index` ?

**Comment by pyrollo** [comment]
Ca ressemble plutôt à un problème de positionnement.

Je ne me souviens plus, il y avait peut être un mécanisme tout fait dans ign pour le positionnement des HUD.

**Comment by pyrollo** [comment]
J'ai été voir dans ign_mesure/hud.lua, le positionnement de l'aide est attaché au bord bas alors que le reste est attaché au bord haut. Donc si la fenêtre est réduite les deux se chevauchent. Un moyen pour éviter ça serait de changer :
```lua
utils.new_hud_group("help", {
	position = {x = 1, y = 1},
	offset = {x = 50, y = -490},
```
En qq chose comme:
```lua
utils.new_hud_group("help", {
	position = {x = 1, y = 0},
	offset = {x = -270, y = ??? },
```

**Comment by kilbith** [comment]
Corrigé.
