### ISSUE TITLE
Les commandes de base s'affichent en haut de l'écran

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#81]
Un changement survenu avec la version de cet après-midi. 
![Capture d’écran (843)](https://user-images.githubusercontent.com/25570981/81075348-87335080-8eea-11ea-91f7-2ec30089ba1b.png)

**Comment by kilbith** [comment]
C’est normal, c’est une idée de Pierre-Yves et je trouve ça mieux comme ça (ne cache pas le bras).

**Comment by pyrollo** [comment]
Ah non, je voyais ça à la suite de la boussole, mais attaché au bord haut pour éviter les chevauchements.

**Comment by forgecitizens** [comment]
Oui c'est ça il faut que ce soit à la suite de la boussole.

**Comment by kilbith** [comment]
Corrigé.
