### ISSUE TITLE
Problème lorsque l'on passe de la carte IGN directement sur World Edit

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#82]
Si je visualise la carte IGN depuis le menu IGN et que je clique sur World Edit :
- La fenêtre world edit s'affiche une seconde puis je reviens automatiquement sur la carte IGN. 
- Le bug a lieu avec la carte ortho et l'image sattelite
- Le bug ne se produit pas si je choisis d'aller sur d'autres onglets.

![Capture d’écran (861)](https://user-images.githubusercontent.com/25570981/81535875-dce47e80-936a-11ea-94fd-c5bd1a32658f.png)

**Comment by pyrollo** [comment]
Corrigé.
