### ISSUE TITLE
Problèmes avec les élements de formspec

### ISSUE THREAD

**Issue by kilbith** [EvidenceBKidscode/kidscode#83]
Comparatif du mod `craftguide` sur Minetest et Kidscode : 

### Minetest

![screenshot_20200519_001456](https://user-images.githubusercontent.com/7883281/82264760-d73bf980-9965-11ea-9b2e-2a464a0dd568.png)

### Kidscode

![screenshot_20200519_001242](https://user-images.githubusercontent.com/7883281/82264773-dc994400-9965-11ea-9e42-1ff1ef4a51a6.png)

- **Problème 1 :** le `field` sur Kidscode est recouvert par un rectangle bleu (le `field` dans ce mod utilise un `style[]`)
- **Problème 2 :** les `background` (rectangles arrondis) sont coupés et les espacements sont différents entre eux.
- **Problème 3 :** le `animated_image` ne fonctionne pas : on ne voit que la 1ère image puis les autres frames sont invisibles (doit être traité en priorité pour la refonte du menu principal).

Il y a définitivement un gros problème de rebase sur `GUIFormspecMenu`.

**Comment by pyrollo** [comment]
Problème 3: On a le même problème dans Minetest, il apparait quand on active "gui_scaling_filter". Je ne sais pas ce que ça implique de le désactiver par défaut.

**Comment by pyrollo** [comment]
Idem pour le Problème 2. Même comportement dans Kidscode que dans Minetest.

**Comment by pyrollo** [comment]
Pour mémoire, le bug est quelque part dans la fonction `guiScalingResizeCached`, fichier `guiscalingfilter.cpp`.

**Comment by pyrollo** [comment]
Problème 1: Ca vient de la gestion de la couleur de fond dans Kidscode. On peut retirer ça, ça a l'air de fonctionner. On risque d'avoir des bugs sur d'anciens formspecs.

**Comment by kilbith** [comment]
`gui_scaling_filter` a été activé pour de bonnes raisons dans le passé, je ne me souviens plus lesquelles (EDIT : pour l'interface du kidsbot il me semble, la qualité était mauvaise quand désactivé). Quoiqu'il en soit ça devrait marcher y compris avec le filtre activé.

Problème 1 : c'est pas très important, tu peux laisser de côté.

**Comment by pyrollo** [comment]
Pour le pb avec gui_scaling_filter faudrait ouvrir une issue côté minetest.

**Comment by kilbith** [comment]
Corrigé.
