### ISSUE TITLE
[crash] mémoire insuffisante en utilisant World Edit

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#84]
En voulant faire un "Remplacer" bloc X par bloc Y sur World Edit le serveur a crashé avec le message ci-dessous : 
![Capture d’écran (910)](https://user-images.githubusercontent.com/25570981/82300324-f31bbb80-99b6-11ea-9d79-fe932cb629e7.png)

Pourtant il ne s'agissait pas d'une grande zone à couvrir.

**Comment by kilbith** [comment]
@pyrollo Il m’apparaît absolument nécessaire d'utiliser LuaJIT 2.1 avec GC64 activé comme dans les builds officiels Windows de Minetest.

**Comment by kilbith** [comment]
Le problème devrait être réglé dans les nouveaux builds.
