### ISSUE TITLE
TNT manquante dans le jeu

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#86]
Il faut remettre la TNT dans le jeu : 
- également à placer dans la boîte à outils du menu IGN. 
- Avec la même configuration initialement prévue (3 tnt maximum autorisées que l'on peut déclencher via le menu avalanche).

**Comment by kilbith** [comment]
Le bloc de TNT ne figure pas dans la whitelist actuelle, d'où l'intérêt de revenir à une blacklist.

**Comment by forgecitizens** [comment]
[kc_list.txt](https://github.com/EvidenceBKidscode/kidscode/files/4696305/kc_list.txt)
J'ai bien tnt node dans la whitelist pourtant

**Comment by kilbith** [comment]
Non : le bloc de TNT c'est `tnt:tnt` et il ne figure pas dans la liste.

**Comment by forgecitizens** [comment]
Par rapport à quelle liste de blocs je dois faire une blacklist ? Actuellement ce qu'il y a dans le jeu comme nodes et items me va très bien j'ai juste besoin que vous remettiez la tnt comme avant je ne comprends pas pourquoi il faut une blacklist pour remettre cette feature...

**Comment by forgecitizens** [comment]
[nodes et items à supprimer.txt](https://github.com/EvidenceBKidscode/kidscode/files/4700297/nodes.et.items.a.supprimer.txt)
[Alias.a.supprimer.txt](https://github.com/EvidenceBKidscode/kidscode/files/4700298/Alias.a.supprimer.txt)

@kilbith moi j'avais déjà fait ces deux blacklist à l'époque et c'était bien les blocs et items à enelever du jeu. Tu peux réutiliser celles-ci du coup

**Comment by kilbith** [comment]
Fait.
