### ISSUE TITLE
[Inventaire][UX] Descendre la page d'un cran sur certains nodes rétractables

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#87]
Lorsque je développe un node rétractable via le bouton "+" je ne vois pas les différentes alternatives du node si toutefois le node est situé tout en bas à droite de la page active. Il faut donc que je descende la page d'un cran via la flèche du bas pour voir les alternatives.
Est-il possible de décaler automatiquement **de deux lignes vers le bas** l'inventaire ?
![Capture d’écran (1022)](https://user-images.githubusercontent.com/25570981/83416180-9392c680-a420-11ea-93b8-d95deb374a46.png)

**Comment by kilbith** [comment]
Nouveau type d'inventaire.
