### ISSUE TITLE
Atterir sur la page de la carte sélectionnée après l'import d'un .zip

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#89]
Après un import d'une carte via le bouton "Importer", et uniquement dans ce cas de figure précis, il faudrait que l'on soit automatiquement redirigé vers la deuxième page du menu principal (celle avec l'option Jouer en 3D et Lancer le cartographe) .

**Comment by pyrollo** [comment]
Fait
