### ISSUE TITLE
Ajouter un bouton "Renommer la carte" dans le menu principal

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#90]
Dans la fenêtre de sélection de la carte, lorsqu'on a sélectionné une carte :
- Ajouter un bouton "Renommer la carte" sous le bouton "Choisir cette carte" ou au-dessus.

Quand on clique dessus la fenêtre déjà existante qui nous demande de donner un titre à la carte apparaît. Le processus standard s'applique ensuite pour nommer la carte.

**Comment by kilbith** [comment]
Fait.
