### ISSUE TITLE
Impossible de zoomer - zoom désactivé par un mod

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#91]
![Capture d’écran (1133)](https://user-images.githubusercontent.com/25570981/85004013-508e5e00-b157-11ea-85db-a1037e7de9d8.png)
Avec le dernier client le message "Le zoom est actuellement désactivé par le jeu ou par un mod" apparaît.

**Comment by pyrollo** [comment]
En relation avec le commit : https://github.com/EvidenceBKidscode/utils/commit/61c103cefdfb19acd9b258464c670c6154e2c613

**Comment by pyrollo** [comment]
Tentative de réparation : https://github.com/EvidenceBKidscode/utils/commit/b37273f59c521c38a494a2fe0822bdbbb882e2a6

Mais ça fait quelques interférences si on avance vite en zoomant.

**Comment by forgecitizens** [comment]
C'est quoi le commit en question j'arrive pas à y accéder Pierre-Yves. C'est quoi la feature qui a été poussée ?

**Comment by pyrollo** [comment]
Une modif qui change l'angle du champ de vision quand le joueur avance vite. Apparament (c'est mal foutu dans MT) quand on spéficie le champ de vision, cela désactive le zoom.

**Comment by pyrollo** [comment]
Corrigé dans le dernier client
