### ISSUE TITLE
Différences à rajouter entre l'installation prof. et élève

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#92]
A la suite de la discussion d'hier, ci-joint les éléments à ne pas afficher dans le menu principal et ingame lors d'une installation élève. 

[Différences_installations_eleve_prof.pdf](https://github.com/EvidenceBKidscode/kidscode/files/4829780/Differences_installations_eleve_prof.pdf)

**Comment by kilbith** [comment]
Je pense pas qu'il soit nécessaire de faire deux clients. On pourrait trouver des solutions comme un bouton pour s'identifier comme enseignant, avec un mot de passe.

**Comment by pyrollo** [comment]
@kilbith ya une option dans l'installeur qui met un settings.

**Comment by kilbith** [comment]
Je me charge de ça alors, faudra juste me donner le setting.

**Comment by pyrollo** [comment]
Ca passe par un parametre de la ligne de commande : 
```
kidscode --install student
```
ou

```
kidscode --install teacher
```

Le setting `install` contient la valeur `student` ou `teacher` selon la ligne de commande.

Le mieux serait de restreindre dans le cas "student", de facon a tout avoir quand on ne passe pas de parametre.

**Comment by kilbith** [comment]
All done.
