### ISSUE TITLE
Crash du jeu en utilisant la feature "supprimer une aire" du bloc utilitaire

### ISSUE THREAD

**Issue by forgecitizens** [EvidenceBKidscode/kidscode#97]
Etapes pour reproduire 
> Ouvrir l'utility block
> Cliquer sur " supprimer une aire "
> Cliquer sur "prendre les positions "
> Faire clic gauche sur un noeud

https://pastebin.com/xpajjdh3

**Comment by pyrollo** [comment]
Corrigé
